#pragma once

#define EE_HANDS

#define QUICK_TAP_TERM 125
#define TAPPING_TERM 125
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD
#define USE_SERIAL_PD2
#define TAPPING_TERM_PER_KEY
#define TAPPING_TOGGLE 3

#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_LIMIT_VAL 120
    #define RGBLIGHT_HUE_STEP 10
    #define RGBLIGHT_SAT_STEP 17
    #define RGBLIGHT_VAL_STEP 17
    #define RGBLIGHT_SLEEP
    #define RGBLIGHT_LAYERS
    #define RGBLIGHT_SPLIT
    #define RGBLIGHT_LAYERS_RETAIN_VAL
#endif
