OLED_ENABLE = yes
OLED_DRIVER = SSD1306
WPM_ENABLE = yes
RGBLIGHT_ENABLE = yes

# optimization
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESCAPE_ENABLE = no
# noitazimitpo