USB_WAIT_FOR_ENUMERATION = no
NO_USB_STARTUP_CHECK = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306

COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESCAPE_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
MUSIC_ENABLE = no
RGBLIGHT_ENABLE = no
SPACE_CADET_ENABLE = no
