# MOUSEKEY_ENABLE = yes
# WPM_ENABLE       = yes
# TAP_DANCE_ENABLE = yes
# VIA_ENABLE       = yes
SWAP_HANDS_ENABLE = yes
# RGBLIGHT_ENABLE   = yes
# OLED_ENABLE       = yes
# OLED_DRIVER       = SSD1306
# LTO_ENABLE        = yes
